import type { Metadata } from "next";

import { getServerSession } from "next-auth/next";

import Navbar from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="dashboard">
      {/* <DotaProfileDataProvider initialState={data}> */}
      <Navbar>
        <li>item test</li>
      </Navbar>
      <a href="/api/auth/signout">Sign out</a>
      {children}
      {/* </DotaProfileDataProvider> */}
    </div>
  );
}
